# Generated by Django 3.2.5 on 2021-09-16 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='profile',
        ),
    ]
